spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/shop
    username: us
    password:
    driver-class-name: org.h2.Driver
  output:
    ansi:
      enabled: always
  messages:
    basename: messages,errors
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
---
logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace
